### ISSUE TITLE
Parameter: hostname

### ISSUE THREAD

**Issue by ferenk** [ivan-rozhon/light-web-server#5]
Adding a hostname parameter would enable to use this web server not only on your local machine but on your LAN.

I've created a very simple implementation for this feature, it works fine.
Feel free to use it, you can merge to your project.

I tried to create a branch, push to your repo and create a pull request, but I don't have any push rights.
Maybe because I'm not a Collaborator, or this repo is not 'Shared'.

So I add it as an attachment.

[index.zip](https://github.com/ivan-rozhon/light-web-server/files/6462802/index.zip)

**Comment by ivan-rozhon** [comment]
That is great idea. I have already merged your pull request that includes hostname parameter.
New version 1.3.0 is now available with these changes.
Thank you.

**Comment by ferenk** [comment]
Great, thank you!
